server:
  port: 9000
language-school:
  schoolUsers:
    - username: michael
      password: geheim
      authorities: ROLE_USER, ROLE_LANGUAGE_GERMAN
    - username: stacey
      password: secret
      authorities: ROLE_USER, ROLE_LANGUAGE_ENGLISH
    - username: admin
      password: admin
      authorities: ROLE_ADMIN
  messages:
    all: Online Language School
    language:  Our available languages are German and English
    german: Willkommen
    english: Welcome