###
GET localhost:9001/uuids
Authorization: Basic drhousehospital drhousehospital

###
POST localhost:9001/patients
Authorization: Basic drhousehospital drhousehospital
Content-Type: application/json

{
  "name": "Lisa",
  "symptom": "headache"
}

###
POST localhost:9001/patients
Content-Type: application/json

{
  "name": "Lisa",
  "symptom": "headache"
}

###
POST localhost:9001/patients
Authorization: Basic drhousehospital drhousehospital
Content-Type: application/json

{
  "name": "Peter",
  "symptom": "bullet wound"
}

###
GET localhost:9001/uuids/Peter
Authorization: Basic drhousehospital drhousehospital
