###
GET http://localhost:9999/
Authorization: Basic apprentice1 password1

###
POST http://localhost:9999/members
Authorization: Basic master secret
Content-Type: application/json

{
  "username": "apprentice1",
  "password": "password1",
  "authorities": ["ROLE_APPRENTICE"]
}

###
GET http://localhost:9999/members
Authorization: Basic master1 password1

###
GET http://localhost:9999/members/apprentice
Authorization: Basic apprentice1 password1